config/routes.rb
Rails.application.routes.draw do
  resources :musics
  devise_for :users
  get 'blogger/about'

  get 'blogger/show'

  resources :photographs
  get 'home/index'
  root 'home#index'

end

app/models/music.rb
class Music < ActiveRecord::Base
  has_attached_file :mp3
  validates_attachment :mp3,
    :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] },
    :file_name => { :matches => [/mp3\Z/] }
end

app/models/photograph.rb
class Photograph < ActiveRecord::Base
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
     
     belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photographs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogger_controller.rb
class BloggerController < ApplicationController
  def about
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:title, :lyrics, :artist, :mp3)
    end
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  before_action :set_photograph, only: [:show, :edit, :update, :destroy]

  # GET /photographs
  # GET /photographs.json
  def index
    @photographs = Photograph.all
  end

  # GET /photographs/1
  # GET /photographs/1.json
  def show
  end

  # GET /photographs/new
  def new
    @photograph = Photograph.new
  end

  # GET /photographs/1/edit
  def edit
  end

  # POST /photographs
  # POST /photographs.json
  def create
    @photograph = Photograph.new(photograph_params)

    respond_to do |format|
      if @photograph.save
        format.html { redirect_to @photograph, notice: 'Photograph was successfully created.' }
        format.json { render :show, status: :created, location: @photograph }
      else
        format.html { render :new }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photographs/1
  # PATCH/PUT /photographs/1.json
  def update
    respond_to do |format|
      if @photograph.update(photograph_params)
        format.html { redirect_to @photograph, notice: 'Photograph was successfully updated.' }
        format.json { render :show, status: :ok, location: @photograph }
      else
        format.html { render :edit }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photographs/1
  # DELETE /photographs/1.json
  def destroy
    @photograph.destroy
    respond_to do |format|
      format.html { redirect_to photographs_url, notice: 'Photograph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photograph
      @photograph = Photograph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photograph_params
      params.require(:photograph).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogger_helper.rb
module BloggerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/blogger/about.html.erb
<div class="container">
    <div class="jumbotron h1-jumbo">
        <h1>LUGAR NI BLOGGER</h1>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <%= render 'home/blogger' %>
        </div>
        <div class="panel-body">
            <header class="business-header">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <img class="img-responsive" src="/assets/3.jpg" alt="">
                            <h1>Si Blogger...</h1>
                            <p class="lead">
                                by <a href="#">R Gregorio</a>
                            </p>
                        </div>
                    </div>
                </div>
            </header>
             <hr>
             
            <div class="row">
            <div class="col-sm-8">
                <h2>Anong ginagawa ko?</h2>
                <p>
                    Isa akong tao, nageexist na ako sa mundo ng 21 years. Minsan ayokong magpakatao, minsan kasi feeling ko Allien ako. Mostly gusto kong umalis, magtravel ba? Ganun.
                    Kahit wala akong pera gusto kong umaalis hindi ko alam kung sadyang gala lang talaga ako. Mahilig din akong bumili ng mga kung anik pero wala akong mga necessity ng isang tao. For example na lang? Wala akong sariling payong
                    ayoko ko kasing bumili feeling ko di ko naman magagamit kaya nakikisukob na lang ako. Mahilig din ako kumaen, madalas ako magcrave ng mga pagkaen na kailangan mo pang dayuhin para lang makaen.
                </p>
                <p>
                    Naniniwala ako sa Love, pero minsan iniisip ko na mas okay na hindi na lang magmahal para hindi masaktan. Playing safe kung baga, madalas kapag medyo malalim na? Umiiwas na ako.
                    Mahirap na! Mahilig akong makinig sa music, music is a part of my daily life. Baka mabasa to ni Ma'am. Lolokohin ako nun. Si paula din kapag nalaman niya tong pinaggagawa ko lolokohin ako nun.
                    Si paula at si Ma'am ang aking napaka bait na taga payong. Minsan TAGAPAYO.
                </p>
                <p>
                    <a class="btn btn-default btn-lg" href="#">Call to Action »</a>
                </p>
            </div>
            <div class="col-sm-4">
                <h2>Contact Us</h2>
                <address>
                    <strong>Start Bootstrap</strong>
                    <br>3481 Melrose Place
                    <br>Beverly Hills, CA 90210
                    <br>
                </address>
                <address>
                    <abbr title="Phone">P:</abbr>(123) 456-7890
                    <br>
                    <abbr title="Email">E:</abbr> <a href="mailto:#">name@example.com</a>
                </address>
            </div>
        </div>
                <div class="well">
                    <p class="lead">
                        
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/blogger/show.html.erb
<h1>Blogger#show</h1>
<p>Find me in app/views/blogger/show.html.erb</p>

app/views/home/_blogger.html.erb
<ul class="list-group">
  <li class="list-group-item"><%= link_to 'Iedit ang mga Larawan', photographs_path, class: "btn" %></li>
  <li class="list-group-item"><%= link_to 'Iedit ang mga #WhoGoat ', photographs_path, class: "btn" %></li>
  <li class="list-group-item"><%= link_to 'Iedit ang mga Kanta', photographs_path, class: "btn" %></li>
  <li class="list-group-item"><%= link_to 'Iedit and mga Tungkol sakin ', photographs_path, class: "btn" %></li>
  <li class="list-group-item"><%= link_to 'Gumawa ng Additional Blogger bukod sa Orihinal ', new_user_registration_path, class: "btn" %></li>
</ul>

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
             <a class="navbar-brand" href="#">TaongCrumble</a>
             <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                    <li><%= link_to 'Si Blogger', blogger_about_path %></li>
                    <li><%= link_to 'Bahay', root_path %></li>
                    <li><%= link_to 'Kuhang Biyak', photographs_path %></li>
                    <li><%= link_to 'Kantang Biyak', root_path %></li>
                    <li><%= link_to '#WhoGoat', root_path %></li>
                    <li><%= link_to 'Out na?', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Bahay', root_path %></li>
                    <li><%= link_to 'Kuhang Biyak', photographs_path %></li>
                    <li><%= link_to 'Kantang Biyak', root_path %></li>
                    <li><%= link_to '#WhoGoat', root_path %></li>
                    <li><%= link_to 'Login Blogger', new_user_session_path %></li>
                <% end %>
             </ul>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<div class="container">
    <div class="jumbotron-header">
        <h2 class="h2-header">KEEP MOVING FORWARD</h2>
    </div>
</div>
<div class="container">
    <div class="panel panel-default">
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'home/header' %>
  
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %> 
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br>
    <%= f.text_field :lyrics %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :mp3 %><br>
    <%= f.file_field :mp3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Musics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Lyrics</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.title %></td>
        <td><%= music.lyrics %></td>
        <td><%= music.artist %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @music.title %>
</p>

<p>
  <strong>Lyrics:</strong>
  <%= @music.lyrics %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @music.artist %>
</p>
<p>
  <strong>Artist:</strong>
  <%= @music.mp3 %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>

app/views/photographs/_form.html.erb
<%= form_for @photograph, html: { multipart: true } do |f| %>
  <% if @photograph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photograph.errors.count, "error") %> prohibited this photograph from being saved:</h2>

      <ul>
      <div class="alert alert-success" role="alert">
        <% @photograph.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Upload Photos", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/photographs/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <h1>BAGUHIN ANG DETALYE</h1>
    </div>
        <div class="panel-body">
            <%= render 'form' %>
            <div class="panel-footer">
                <%= link_to 'BUMALIK', photographs_path, class: "btn btn-default btn-block" %>
            </div>
        </div>
</div>

app/views/photographs/index.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
  <p id="notice"><%= notice %></p>
  <div class="panel-heading jumbotron h1-panel">
    <h1><span class="h1-panel">MAGULONG MGA LARAWAN</span></h1>
    <%= link_to 'BAGONG LARAWAN', new_photograph_path, class: "btn btn-info" %>
  </div>  
    <% @photographs.each do |photograph| %>
        <div class="container-fluid pane-center">
        <div class="panel panel-default">
          <div class="panel-body">
                <%= image_tag photograph.image.url(:medium) %><br><br>
                <div class="panel-footer">
                  <%= photograph.title %><br>
                  <%= photograph.description %><br>
                  <% if user_signed_in? %>
                    <%= link_to 'Show', photograph %><br>
                    <%= link_to 'Edit', edit_photograph_path(photograph) %><br>
                    <%= link_to 'Destroy', photograph, method: :delete, data: { confirm: 'Are you sure?' } %></td><br>
                  <% else %>
                  <% end %>
                </div>
            </div>
          </div>
        <br>
        </div>
    <% end %>
</div>

app/views/photographs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>Bagong larawan!</h1></div>
  <div class="panel-body">

    <%= render 'form' %>
    <div class="panel-footer">
        <%= link_to 'Back', photographs_path %>
    </div>
</div>

app/views/photographs/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <%= image_tag @photograph.image.url(:medium) %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= @photograph.title %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= @photograph.description %>
  </p>
  
</div>